<a href="https://colab.research.google.com/github/osori-magu/Nunpy-Onshot/blob/master/Numpy_%ED%95%9C%EB%B0%A9%EC%97%90_%EB%B0%B0%EC%9A%B0%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 제대로 배우기


In [ ]:
import numpy as np

## NumPy 특징

## 배열생성

### 리스트로 배열 만들기

### 배열 생성 및 초기화
- zeros(): 모든 요소를 0으로 초기화

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

- ones(): 모든 요소를 1로 초기화

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

- full(): 모든 요소를 지정한 값으로 초기

In [ ]:
np.full((3,3),1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

- eye(): 단위행렬(identity matrix)생성
  - 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 - empty(): 초기화 되지 않은 배열 생성
  - 초기화가 없어서 배열 생성 비용이 저렴하고 빠름
  - 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있

In [ ]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

- _like(): 지정된 배열과 shape가 같은 행렬 생성 

   - np.zeros_like()
   - np.ones_like()
   - np.full_like()
   - np.empty_like()



In [ ]:
a1 = np.array([4,5,6,4,5])
np.zeros_like(a1)

array([0, 0, 0, 0, 0])

In [ ]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)

np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
a3 = np.array([
               [[1,2,3,], [4,5,6,], [7,8,9] ],
               [[1,2,3,], [4,5,6,], [7,8,9] ],
               [[1,2,3,], [4,5,6,], [7,8,9] ]
               ])

np.full_like(a3, 10)

array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

벡터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용된다. 선형 대수에 적용되는 벡터화 연산에 대해서는 나중에 보다 자세히 설명한다.

### 생성한 값으로 배열 생성

- arange(): 정수 범위로 배열 생성

In [ ]:
np.arange(0, 30, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

 - linspace(): 범위 내에서 균등 간격의 배열 생성


In [ ]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

 - logspace(): 범위 내에서 균등간격으로 로그 스케일로 배열 생성


In [ ]:
np.logspace(0.1, 1, 20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

### 랜덤값으로 배열 생성 

|함수|설명   |
|---|---|
|seed|난수 발생을 위한 시드 지정|
|permutation|순서를 임의로 바꾸거나 임의의 순열 반환|
|shuffle   |리스트나 배열의 순서를 뒤썩음   |
|random   |랜덤한 수의 배열 생성   |
|rand   |균등분포에서 표본 추출   |
|randint   |주어진 최소/최대 범위의 난수 추출   |
|bionomial|표준편차가1, 평균값 0인 정규분포의 표본 추출|
|normal   |정규분포(가우시안)에서 표본추출   |
|beta   |베타분포에서 표본 추출   |
|chisquare   |카이제곱분포에서 표본 추출   |
|gamma   |감마분포에서 표본 추출  |
|uniform   |균등(0,1)분포에서 포본추출  |

 - random.random(): 랜덤한 수의 배열 생성

In [ ]:
np.random.random((3,3))

array([[0.69042284, 0.061884  , 0.22256309],
       [0.7125539 , 0.50958   , 0.85172066],
       [0.59976871, 0.81775006, 0.18537027]])

 - np.random.randint(): 일정한 구간의 랜덤 정수의 배열 생성

In [ ]:
np.random.randint(0,10, (3,3))

array([[3, 6, 2],
       [3, 7, 9],
       [3, 9, 6]])

 - random.normal(): 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성 
 - 평균 = 0, 표준편차=1, 3 x 3 배열
 

In [ ]:
#np.random.normal(0,1, (3,3))
np.random.normal(0,1, size=(3,3))

array([[-1.13610845, -0.98515166, -0.38009469],
       [ 0.88730634, -1.73374156, -0.64965403],
       [-1.7255768 ,  0.14725066, -1.32273086]])

 - random.rand(): 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생

In [ ]:
np.random.rand(3,3)

array([[0.98369829, 0.07436331, 0.29996361],
       [0.99537375, 0.96106931, 0.6499512 ],
       [0.04833778, 0.04992918, 0.59937316]])

 - random.rand():표준정규분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성
 

In [ ]:
np.random.randn(3,3)

array([[ 0.80737039,  1.02131233,  0.90727482],
       [-0.86455741,  0.0998733 ,  0.34942583],
       [ 1.84541007,  0.78900804,  1.49238612]])

### 표준 데이터 타입

|데이터타입|설명|
|---|---|
|bool_|바이트로 저장된 Boolean으로 True or False값을 가짐|
|int_|Integer type|
|intc|C언어에서 사용되는 int와 동일(일반적으로 int32 또는 int64)|
|intp|인덱싱에 사용되는 정수(C언어에서 sszie_t와 동일; 일반적으로 int32 또는 int64)|
|int8|Byte(-128 to127)|
|int16|Integer(-32768 to 32767)|
|int32|Integer(-2147483648 to 2147483647)
|int64|Integer(-9223372036854775808 to 9223372036854775807)|
|uint8|부호 없는 정수/Unsigned integer (0 to 255)|
|uint16|부호 없는 정수/Unsigned integer (0 to 65535)|
|uint32|부호 없는 정수/Unsigned integer (0 to 4294967295)|
|uint64|부호 없는 정수/Unsigned integer (0 to 18446744073709551615)|
|float16|반정밀 부동 소수점(Half precision float):부호비트, 5비트 지수, 10비트 가수|
|float32|단정밀 부동 소수점(Single precision float):부호비트 8비트 지수, 23비트 가수|
|float64|배정밀 부동 소수점(Double precision float): 부호비트, 11비트 지수, 52비트 가수|
|float_|float64를 줄여서 표현|
|complex64|복소수(Complex number), 두 개의 32비트 부동 소수점으로 표현|
|complex128|복소, 두 개의 64비트 부동 소수점으로 표현|
|complex_|complex128를 줄여서 표현|


In [ ]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
np.full((3,3), 1.0, dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 날짜/시간 배열 생성 

|코드|의미|상대적 시간범위|절대적 시간범위|
|---|---|---|---|
|```Y``` |연     |±9.2e18 years    |[9.2e18 BC, 9.2e18 AD]    |
|```M``` |월     |±7.6e17 years    |[7.6e17 BC, 7.6e17 AD]    |
|```W``` |주     |±1.7e17 years    |[1.7e17 BC, 1.7e17 AD]    |
|```D``` |일     |±2.5e16 years    |[2.5e16 BC, 2.5e16 AD]    |
|```h``` |시     |±1.0e15 years    |[1.0e15 BC, 1.0e15 AD]    |
|```m``` |분     |±1.7e13 years    |[1.7e13 BC, 1.7e13 AD]    |
|```s``` |초     |±2.9e11 years    |[2.9e11 BC, 2.9e11 AD]    |
|```ms```|밀리초|±2.9e8 years   |[ 2.9e8 BC, 2.9e8 AD]    |
|```us```|마이크로초|±2.9e5 years    |[ 290301 BC, 294241 AD]    |
|```ns```|나노초|±292 years    |[ 1678 AD, 2262 AD]    |
|```ps```|피코초|±106 days    |[ 1969 AD, 1970 AD]    |
|```fc```|펨토초|±2.6 hours    |[ 1969 AD, 1970 AD]    |
|```as```|아토초|±9.2 seconds    |[ 1969 AD, 1970 AD]   |

In [ ]:
date = np.array('2020-01-01', dtype=np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [ ]:
date + np.arange(3)

array(['2020-01-01', '2020-01-02', '2020-01-03'], dtype='datetime64[D]')

In [ ]:
datetime = np.datetime64('2020-06-01 12:00')
datetime

numpy.datetime64('2020-06-01T12:00')

In [ ]:
datetime = np.datetime64('2020-01-01 12:00:12.34', 'ns')
datetime

numpy.datetime64('2020-01-01T12:00:12.340000000')

## 배열조희


### 배열 속성 정보 

In [ ]:
def array_info(array):
  print(array)
  print('ndim:', array.ndim)
  print('shape:', array.shape)
  print('dtype:', array.dtype)
  print('size:', array.size)
  print('itemsize:', array.itemsize)
  print('nbytes:', array.nbytes)
  print('strides:', array.strides)

In [ ]:
a1 = np.array([4,5,6,4,5])
array_info(a1)
# ndim은 차원의 개수
# shape은 5개의 element가 있다는것/ 1행 5열(1row 5columns)
# dtype int인 정수값 사용
# size는 5개의 element를 말하조.
# itemsize는 각 하나의 item의 byte크기를 말함 즉, 8byte
# nbytes는 40의미가 각 itemsize 8 * 5개
# 한개 elements를 넘어가기 위해서는 8byte가 필요함 / 3차원->2차원->1차원 넘어갈때 필요한 bytes크기

[4 5 6 4 5]
ndim: 1
shape: (5,)
dtype: int64
size: 5
itemsize: 8
nbytes: 40
strides: (8,)


In [ ]:
array_info(a2)
# strides 다음 row로 넘어갈때 필요한게 24bytes
# 3차원->2차원->1차원 넘어갈때 필요한 bytes크기

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape: (3, 3)
dtype: int64
size: 9
itemsize: 8
nbytes: 72
strides: (24, 8)


In [ ]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim: 3
shape: (3, 3, 3)
dtype: int64
size: 27
itemsize: 8
nbytes: 216
strides: (72, 24, 8)


### 인덱싱(Indexing)

In [ ]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[4 5 6 4 5]
4
6
5
4


In [ ]:
print(a2)
print(a2[0,0])
print(a2[0,2])
print(a2[1,-1])
print(a2[2,-2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
6
8


In [ ]:
print(a3)
print(a3[0,0,0])
print(a3[1,1,1])
print(a3[1,2,2])
print(a3[1,-1,-2])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
5
9
8


### 슬라이싱(Slicing)

 - 슬라이싱 구문: **```a[start:stop:step]```**
 - 기본값: start =0, stop =ndim, step=1


In [ ]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[::2])
print(a1[::-1])

[4 5 6 4 5]
[4 5]
[4 5 6 4 5]
[4]
[4 6 5]
[5 4 6 5 4]


In [ ]:
print(a2)
print('-----')
print(a2[1])
print('-----')

print(a2[1, :])

print('-----')
print(a2[:2, :2])

print('-----')
print(a2[1:,  ::-1])

print('-----')
print(a2[::-1, ::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-----
[4 5 6]
-----
[4 5 6]
-----
[[1 2]
 [4 5]]
-----
[[6 5 4]
 [9 8 7]]
-----
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### Boolean Indexing
- 배열 각 요소의 선택 여부를 True or False로 지정
- True 값인 인덱스의 값만 조회

In [ ]:
print(a1)
bi = [False, True, True, False, True]
print(a1[bi])
bi = [True, False, True, True, False]
print(a1[bi])

[4 5 6 4 5]
[5 6 5]
[4 6 4]


In [ ]:
print(a2)
bi = np.random.randint(0,2, (3,3), dtype=bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False  True]
 [ True False False]
 [ True False  True]]
[3 4 7 9]


### Fancy Indexing

In [ ]:
print(a1)
print(a1[0],a1[2])
ind = [0,2]
print(a1[ind])
ind = np.array([
                [0,1],
                [2,0]
              ])
print(a1[ind])

[4 5 6 4 5]
4 6
[4 6]
[[4 5]
 [6 4]]


In [ ]:
print(a2)
row = np.array([0,2])
col = np.array([1,2])
print('=======')

print(a2[row, col])

print('=======')
print(a2[row, :])
print('=======')
print(a2[:, col])
print('=======')


print(a2[row, 1])

print('=======')
print(a2[2, col])
print('=======')
print(a2[row, 1:])
print('=======')
print(a2[1:, col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[2 8]
[8 9]
[[2 3]
 [8 9]]
[[5 6]
 [8 9]]


## 배열 값 삽입/수정/삭제/복사 



### 배열 값 삽입 

 - ```insert():```: 배열의 특정 위치에 값 삽입 
 - axis를 지정하지 않으면 1차원 배열로 변환
 - 추가할 방향을 axis로 지정
 - 원본 배열 변경없이 새로운 배열 반환
 

In [ ]:
print(a1)
b1 = np.insert(a1, 0, 10)
print(b1)
print(a1)
c1 = np.insert(a1, 2, 10)
print(c1)

[4 5 6 4 5]
[10  4  5  6  4  5]
[4 5 6 4 5]
[ 4  5 10  6  4  5]


In [ ]:
print(a2)
print('===')
b2 = np.insert(a2, 1,10, axis=0)
print(b2)
print('===')
c2 = np.insert(a2,1, 10, axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
===
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
===
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정 
 - 배열의 인덱싱으로 접근하여 값 수정

In [ ]:
print(a1)
a1[0] = 1
a1[1] = 2
a1[2] = 3
print(a1)
a1[:1] = 9
print(a1)


[4 5 6 4 5]
[1 2 3 4 5]
[9 2 3 4 5]


In [ ]:
i = np.array([1,3,4])
a1[i] = 0
a1[i] += 4

print(a1)

[9 4 3 4 4]


In [ ]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)
a2[0,0]=1
print('===')
a2[1,1]=2
print(a2)
a2[2,2]=3
print('===')

a2[0]=1
print(a2)
print('===')
a2[1:, 2] = 9
print(a2)
print('===')
a2[row, col] = 0
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
===
[[1 2 3]
 [4 2 6]
 [7 8 9]]
===
[[1 1 1]
 [4 2 6]
 [7 8 3]]
===
[[1 1 1]
 [4 2 9]
 [7 8 9]]
===
[[1 0 1]
 [4 2 9]
 [7 8 0]]


### 배열 값 삭제 
- delete(): 배열의 특정 위치에 값 삭제
- axis를 지정하지 않으면 1차원 배열로 변환
- 삭제할 방향을 axis로 지정
- 원본 배열 변경없이 새로운 배열 반환


In [ ]:
print(a1)
b1 = np.delete(a1,1)
print(b1)
print(a1)

[9 4 3 4 4]
[9 3 4 4]
[9 4 3 4 4]


In [ ]:
print(a2)
print('===')
print()
b2 = np.delete(a2, 1, axis=0)
print(b2)
print('===')
c2 = np.delete(a2, 1, axis=1)
print(c2)

[[1 0 1]
 [4 2 9]
 [7 8 0]]
===

[[1 0 1]
 [7 8 0]]
===
[[1 1]
 [4 9]
 [7 0]]


### 배열 복사
- 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님 


In [ ]:
print(a2)
print('===')
print(a2[:2, :2])
a2_sub = a2[:2, :2]
print('===')
print(a2_sub)
print('===')
a2_sub[:, 1] = 0
print(a2_sub)
print('===')
print(a2)


[[1 0 1]
 [4 2 9]
 [7 8 0]]
===
[[1 0]
 [4 2]]
===
[[1 0]
 [4 2]]
===
[[1 0]
 [4 0]]
===
[[1 0 1]
 [4 0 9]
 [7 8 0]]


 - copy(): 배열이나 하위 배열 내의 값을 명시적으로 복사

In [ ]:
print(a2)
print('===')
a2_sub_copy = a2[:2, :2].copy()
print(a2_sub_copy)
a2_sub_copy[:, 1]=1
print('===')
print(a2_sub_copy)
print(a2)

[[1 0 1]
 [4 0 9]
 [7 8 0]]
===
[[1 0]
 [4 0]]
===
[[1 1]
 [4 1]]
[[1 0 1]
 [4 0 9]
 [7 8 0]]


## 배열 변환 


### 배열 전치 및 축 변경

In [ ]:
print(a2)
print('===')
print(a2.T)

[[1 0 1]
 [4 0 9]
 [7 8 0]]
===
[[1 4 7]
 [0 0 8]
 [1 9 0]]


In [ ]:
print(a3)
print('==================')
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [ ]:
print(a2)
print('==================')
print(a2.swapaxes(1,0))

[[1 0 1]
 [4 0 9]
 [7 8 0]]
[[1 4 7]
 [0 0 8]
 [1 9 0]]


In [ ]:
print(a3)
print('==================')
print(a3.swapaxes(0,1))
print('==================')
print(a3.swapaxes(1,2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


### 배열 재구조화

- reshape(): 배열의 형상을 변경

In [ ]:
n1 = np.arange(1, 10)
print(n1)
print(n1.reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


- newaxis(): 새로운 축 추가

In [ ]:
print(n1)
print('==================')

print(n1[np.newaxis, :5])
print('==================')

print(n1[:5, np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### 배열 크기 변경

- 배열 모양만 변경

In [ ]:
n2 = np.random.randint(0, 3, (2,5))
print(n2)
print('==================')
n2.resize((5,2))
print((n2))

[[1 1 0 1 1]
 [2 1 0 1 2]]
[[1 1]
 [0 1]
 [1 2]
 [1 0]
 [1 2]]


 - 배열 크기 증가
 - 남은 공간은 0으로 채워짐

In [ ]:
n2.resize((5,5))
print((n2))

[[1 1 0 1 1]
 [2 1 0 1 2]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


- 배열 크기 감소
- 포함되지 않은 값은 삭제됨


In [ ]:
n2.resize((4,4))
print(n2)
print('==================')
n2.resize((3,3))
print(n2)

[[1 1 0 1]
 [1 2 1 0]
 [1 2 0 0]
 [0 0 0 0]]
[[1 1 0]
 [1 1 2]
 [1 0 1]]


### 배열추가

- append(): 배열의 끝에 값 추가

In [ ]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
print('==================')
b2 = np.arange(10,19).reshape(3,3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


- axis 지정이 없으면 1차원 배열 형태로 변형되어 결

In [ ]:
c2 = np.append(a2, b2)
print('==================')
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


- axis를 0으로 지정
- shape[0]을 제외한 나머지 shape는 같아야 

In [ ]:
c2 = np.append(a2, b2, axis=0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


- axis를 1로 지정
- shape[1]을 제외한 나머지 shape은 같아야 함 

In [ ]:
c2 = np.append(a2, b2, axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결 

- concatenate(): 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [ ]:
a1 = np.array([1,3,5])
b1 = np.array([2,4,6])
np.concatenate([a1,b1])


array([1, 3, 5, 2, 4, 6])

In [ ]:
c1 = np.array([7,8,9])
np.concatenate([a1,b1,c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [ ]:
a2 = np.array([
              [1,2,3],
              [4,5,6]])
np.concatenate([a2,b2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

- vstack(): 수직 스택(vertical stack), 1차원으로 연결 

In [ ]:
np.vstack([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

- hstack(): 수평 스택(horizontal stack), 2차원으로 연

In [ ]:
np.hstack([a2,a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

- dstack(): 깊이 스택(depth stack), 3차원으로 연결


---



In [ ]:
np.dstack([a2, a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

- stack(): 새로운 차원으로 연결 


In [ ]:
np.stack([a2,a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

## 배열분할 

- split(): 배열분할 

In [ ]:
a1 = np.arange(0,10)
print(a1)
b1, c1 = np.split(a1, [5])
print('---------------')
print(b1,c1)
print('---------------')
b1, c1 = np.split(a1, [2,4,6,8])


[0 1 2 3 4 5 6 7 8 9]
---------------
[0 1 2 3 4] [5 6 7 8 9]
---------------


ValueError: ignored

- vsplit(): 수직분할, 1차원으로 분

In [ ]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2, c2 = np.vsplit(a2, [2])
print('---------------')
print(b2)
print('---------------')

print(c2)

- hsplit(): 수평분할, 2차원으로 분

In [ ]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2, c2 = np.hsplit(a2, [2])
print('---------------')
print(b2)
print('---------------')

print(c2)

- dsplit(): 깊이 분할, 3차원으로 분할

In [ ]:
a3 = np.arange(1,28).reshape(3,3,3)
print(a3)
print('---------------')

b3, c3 = np.dsplit(a3, [2])
print(b3)
print('---------------')
print(c3)

## 배열 연산 

- Numpy의 배열 연산은 벡터화(vectorized)연산을 사용
- 일반적으로 Numpy의 범용 함수(universal functions)를 통해 구현 
- 배열 요소에 대한 반복적인 계산을 효율적으로 수행 

### 브로드캐스팅(Broadcasting)

In [ ]:
a1 = np.array([1,2,3])
print(a1)
print('---------------')

print(a1 + 5)
print('---------------')

a2 = np.arange(1,10).reshape(3,3)
print(a2)
print('---------------')
print(a1+a2)

b2 = np.array([1,2,3]).reshape(3,1)
print(b2)
print(a1 + b2)

### 산술연산(Arithmetic Operators)

|연산자|범용 함수|설명|
|---|---|---|
|+|np.add|덧셈|
|-|np.subtract|뺄셈|
|-|np.negative|단항 음수|
|*|np.multiply|곱셈|
|/|np.divide|나눗셈|
|//|np.floor_divide|나눗셈 내림|
|**|np.power|지수 연산|
|%|np.mod|나머지 연산|

In [ ]:
a1 = np.arange(1,10)
print(a1)
print('---------------\n')

print(a1 + 1)
print('---------------')
print(np.add(a1,10))
print('---------------\n')

print(a1 - 2)
print('---------------')
print(np.subtract(a1,10))

print('---------------\n')
print(a1 * 2)
print(np.multiply(a1,2))
print('---------------\n')

print(np.divide(a1,2))
print('---------------')
print(a1/2)

print('---------------\n')
print(a1//2)
print(np.floor_divide(a1,2))
print('---------------\n')

print(a1 **2)
print(np.power(a1,2))
print('---------------\n')

print(a1 % 2)
print(np.mod(a1,2))


In [ ]:
a1 = np.arange(1,10)
print(a1)
b1 = np.random.randint(1, 10, size=9)
print(b1)
print('---------------')

print(a1 + b1)
print('---------------')
print(a1-b1)
print('---------------')
print(a1*b1)
print('---------------')
print(a1/b1)
print('---------------')
print(a1//b1)
print('---------------')
print(a1**b1)
print('---------------')
print(a1%b1)

[1 2 3 4 5 6 7 8 9]
[3 5 5 8 4 6 4 8 3]
---------------
[ 4  7  8 12  9 12 11 16 12]
---------------
[-2 -3 -2 -4  1  0  3  0  6]
---------------
[ 3 10 15 32 20 36 28 64 27]
---------------
[0.33333333 0.4        0.6        0.5        1.25       1.
 1.75       1.         3.        ]
---------------
[0 0 0 0 1 1 1 1 3]
---------------
[       1       32      243    65536      625    46656     2401 16777216
      729]
---------------
[1 2 3 4 1 0 3 0 0]


In [ ]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.random.randint(1,10, size=(3,3))
print('---------------')
print(b2)
print('---------------')
print(a2 + b2)
print('---------------')

print(a2 - b2)

print('---------------')
print(a2 * b2)

print('---------------')
print(a2 / b2)

print('---------------')
print(a2 // b2)

print('---------------')
print(a2 ** b2)

print('---------------')
print(a2 % b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------------
[[5 5 4]
 [2 6 2]
 [1 9 5]]
---------------
[[ 6  7  7]
 [ 6 11  8]
 [ 8 17 14]]
---------------
[[-4 -3 -1]
 [ 2 -1  4]
 [ 6 -1  4]]
---------------
[[ 5 10 12]
 [ 8 30 12]
 [ 7 72 45]]
---------------
[[0.2        0.4        0.75      ]
 [2.         0.83333333 3.        ]
 [7.         0.88888889 1.8       ]]
---------------
[[0 0 0]
 [2 0 3]
 [7 0 1]]
---------------
[[        1        32        81]
 [       16     15625        36]
 [        7 134217728     59049]]
---------------
[[1 2 3]
 [0 5 0]
 [0 8 4]]


#### 절대값 연산(Absolute Function)
- absolute(), abs(): 내장된 절대값 함

In [ ]:
a1 = np.random.randint(-10, 10, size=5)
print(a1)
print('---------------')
print(np.absolute(a1))
print(np.abs(a1))

[5 6 9 7 1]
---------------
[5 6 9 7 1]
[5 6 9 7 1]


#### 제곱/제곱근 함수
- square, sqrt: 제곱, 제곱근 함수 

In [ ]:
print(a1)
print('---------------')
print(np.square(a1))
print('---------------')
print(np.sqrt(a1))

#### 지수와 로그함수(Exponential and Log Function)

In [ ]:
a1 = np.random.randint(1,10,size=5)
print(a1)
print('---------------')
print(np.exp(a1))  # exponential 값을 구합니다.
print('---------------')

print(np.exp2(a1)) #입력 Array값에 대해 2의 n 거듭제곱으로 계산
print('---------------')

print(np.power(a1, 2)) # 첫번째로 입력된 array의 값들을 두번째 입력된 배열의 값으로 거듭 제곱 계산

In [ ]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

#### 삼각함수(Trigonometrical Function)

|함수|설명|
|---|---|
|np.sin(array)|요소별 사인|
|np.cos(array)|요소별 코사인|
|np.tan(array)|요소별 탄젠트|
|np.arcsin(array)|요소별 아크 사인|
|np.arccos(array)|요소별 아크 사인|
|np.arctan(array)|요소별 아크 탄젠트|
|np.arctan2(array1, array2)|요소별 아크 탄젠트 array1/array2|
|np.sinh(array)|요소별 하이퍼볼릭사인|
|np.cosh(array)|요소별 하이퍼볼릭 코사인|
|np.tanh(array)|요소별 하이퍼볼릭 탄젠트|
|np.arcsinh(array)|요소별 하이퍼볼릭 아크 사인|
|np.arccosh(array)|요소별 하이퍼볼릭 아크 코사인|
|np.arctanh(array)|요소별 하이퍼볼릭 아크 탄젠트|
|np.deg2rad(array)|요소별 각도에서 라디안 변환|
|np.rad2deg(array)|요소별 라디안에서 각도 변환|
|np.hypot(array, array2)|요소별 유클리드 거리계산|

In [ ]:
t = np.linspace(0, np.pi,3)
print(t)
print('==================')
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [ ]:
x = [-1, 0, 1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

### 집계함수(Aggregate Functions)
|함수|NaN안전모드|설명|
|---|---|---|
|np.sum|np.nansum|요소의합 계산|
|np.cumsum|np.nancumsum|요소의 누적 합|
|np.diff|N/A|요소의 차분|
|np.prod|np.nanprod|요소의 곱 계산|
|np.cumprod|np.nancumprod|요소의 누적 곱|
|np.dot|N/A|점 곱(dot product)|
|np.matmul|N/A|행렬 곱|
|np.tensordot|N/A|텐서곱(tensor product)|
|np.cross|N/A|벡터곱(cross product)|
|np.inner|N/A|내적(inner product)|
|np.outer|N/A|외적(outer product)|
|np.mean|np.nanmean|요소의 평균 계산|
|np.std|np.nanstd|표준 편차 계산|
|np.var|np.nanvar|분산 계산|
|np.min|np.nanmin|최소값|
|np.max|np.nanmax|최대값|
|np.argmin|np.nanargmin|최소값 인덱스|
|np.argmax|np.nanargmax|최대값 인덱|

#### sum(): 합 계

In [ ]:
a2 = np.random.randint(1,10,size=(3,3))
print(a2)
print('==============================')
print(a2.sum(), np.sum(a2))
print('==============================')
print(a2.sum(axis=0), np.sum(a2, axis=0))
print('==============================')
print(a2.sum(axis=1), np.sum(a2, axis=1))


[[7 9 5]
 [6 9 7]
 [7 1 6]]
57 57
[20 19 18] [20 19 18]
[21 22 14] [21 22 14]


#### cumsum(): 누적합 계산 


In [ ]:
print(a2)
print('==============================')
print( np.cumsum(a2))
print('==============================')
print( np.cumsum(a2, axis=0))
print('==============================')
print(np.cumsum(a2, axis=1))

[[7 9 5]
 [6 9 7]
 [7 1 6]]
[ 7 16 21 27 36 43 50 51 57]
[[ 7  9  5]
 [13 18 12]
 [20 19 18]]
[[ 7 16 21]
 [ 6 15 22]
 [ 7  8 14]]


In [ ]:
#### diff(): 차분 계산

In [ ]:
print(a2)
print('==============================')
print( np.diff(a2))
print('==============================')
print( np.diff(a2, axis=0))
print('==============================')
print(np.diff(a2, axis=1))

[[7 9 5]
 [6 9 7]
 [7 1 6]]
[[ 2 -4]
 [ 3 -2]
 [-6  5]]
[[-1  0  2]
 [ 1 -8 -1]]
[[ 2 -4]
 [ 3 -2]
 [-6  5]]


*이탤릭체 텍스트*#### prod(): 곱 계산 

2차원 배열의 경우 axis=0 이면 같은 열(column)의 위*아래 방향으로 배열 원소 간 곱하며, axis=1 이면 같은 행(row)의 왼쪽*오른쪽 원소 간 곱을 합니다.



In [ ]:
print(a2,a2.shape)
print('==============================')
print(np.prod(a2))
print('==============================')
print( np.prod(a2, axis=0))
print('==============================')
print(np.prod(a2, axis=1))

[[7 9 5]
 [6 9 7]
 [7 1 6]] (3, 3)
5000940
[294  81 210]
[315 378  42]


#### cumprod(): 누접곱 계산

In [ ]:
print(a2,a2.shape)
print('==============================')
print(np.cumprod(a2))
print('==============================')
print( np.cumprod(a2, axis=0))
print('==============================')
print(np.cumprod(a2, axis=1))

[[7 9 5]
 [6 9 7]
 [7 1 6]] (3, 3)
[      7      63     315    1890   17010  119070  833490  833490 5000940]
[[  7   9   5]
 [ 42  81  35]
 [294  81 210]]
[[  7  63 315]
 [  6  54 378]
 [  7   7  42]]


#### dot()/matmul(): 점곱/행렬곱 계산

In [ ]:
print(a2)
b2 = np.ones_like(a2)
print('==============')
print(b2)
print('==============')
print(np.dot(a2,b2))
print('==============')
print(np.matmul(a2,b2))




[[7 9 5]
 [6 9 7]
 [7 1 6]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[21 21 21]
 [22 22 22]
 [14 14 14]]
[[21 21 21]
 [22 22 22]
 [14 14 14]]


#### tensordot():텐서곱 계산

In [ ]:
print(a2)
print('==============')
print(b2)
print('==============')
print(np.tensordot(a2,b2))
print('==============')
print(np.tensordot(a2,b2, axes=0))
print('==============')
print(np.tensordot(a2,b2, axes=1))




[[7 9 5]
 [6 9 7]
 [7 1 6]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
57
[[[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[9 9 9]
   [9 9 9]
   [9 9 9]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]]


 [[[6 6 6]
   [6 6 6]
   [6 6 6]]

  [[9 9 9]
   [9 9 9]
   [9 9 9]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]]


 [[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[6 6 6]
   [6 6 6]
   [6 6 6]]]]
[[21 21 21]
 [22 22 22]
 [14 14 14]]


#### cross(): 벡터곱

In [ ]:
x = [1,2,3]
y = [4,5,6]
print(np.cross(x,y))

[-3  6 -3]


#### inner() / outer(): 내적/ 외적 

In [ ]:
print(a2)
print('==============')
print(b2)
print('==============')
print(np.inner(a2,b2)) # dot product와 동일한 결과 
print('==============')
print(np.outer(a2,b2))
print('==============')





[[7 9 5]
 [6 9 7]
 [7 1 6]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[21 21 21]
 [22 22 22]
 [14 14 14]]
[[7 7 7 7 7 7 7 7 7]
 [9 9 9 9 9 9 9 9 9]
 [5 5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6 6]
 [9 9 9 9 9 9 9 9 9]
 [7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7]
 [1 1 1 1 1 1 1 1 1]
 [6 6 6 6 6 6 6 6 6]]


#### mean(): 평균계산

In [ ]:
print(a2)
print('==============')
print(np.mean(a2))
print('==============')
print(np.mean(a2, axis=0))
print('==============')
print(np.mean(a2, axis=1))




[[7 9 5]
 [6 9 7]
 [7 1 6]]
6.333333333333333
[6.66666667 6.33333333 6.        ]
[7.         7.33333333 4.66666667]


#### std(): 표준편차 계산

In [ ]:
print(a2)
print('==============')
print(np.std(a2))
print('==============')
print(np.std(a2, axis=0))
print('==============')
print(np.std(a2, axis=1))




[[7 9 5]
 [6 9 7]
 [7 1 6]]
2.260776661041756
[0.47140452 3.77123617 0.81649658]
[1.63299316 1.24721913 2.62466929]


#### var(): 분산계산

In [ ]:
print(a2)
print('==============')
print(np.var(a2))
print('==============')
print(np.var(a2, axis=0))
print('==============')
print(np.var(a2, axis=1))




[[7 9 5]
 [6 9 7]
 [7 1 6]]
5.111111111111111
[ 0.22222222 14.22222222  0.66666667]
[2.66666667 1.55555556 6.88888889]


#### min(): 최소값

In [ ]:
print(a2)
print('==============')
print(np.min(a2))
print('==============')
print(np.min(a2, axis=0))
print('==============')
print(np.min(a2, axis=1))




[[7 9 5]
 [6 9 7]
 [7 1 6]]
1
[6 1 5]
[5 6 1]


#### min(): 최대값

In [ ]:
print(a2)
print('==============')
print(np.max(a2))
print('==============')
print(np.max(a2, axis=0))
print('==============')
print(np.max(a2, axis=1))




[[7 9 5]
 [6 9 7]
 [7 1 6]]
9
[7 9 7]
[9 9 7]


#### argmin(): 최소값 인덱스

In [ ]:
print(a2)
print('==============')
print(np.argmin(a2))
print('==============')
print(np.argmin(a2, axis=0))
print('==============')
print(np.argmin(a2, axis=1))




[[7 9 5]
 [6 9 7]
 [7 1 6]]
7
[1 2 0]
[2 0 1]


#### argmax(): 최대값 인덱스

In [ ]:
print(a2)
print('==============')
print(np.argmax(a2))
print('==============')
print(np.argmax(a2, axis=0))
print('==============')
print(np.argmax(a2, axis=1))




[[7 9 5]
 [6 9 7]
 [7 1 6]]
1
[0 0 1]
[1 1 0]


#### median(): 중앙값

In [ ]:
print(a2)
print('==============')
print(np.median(a2))
print('==============')
print(np.median(a2, axis=0))
print('==============')
print(np.median(a2, axis=1))




[[7 9 5]
 [6 9 7]
 [7 1 6]]
7.0
[7. 9. 6.]
[7. 7. 6.]


#### percentile(): 백분의수 

In [ ]:
a1 = np.array([0,1,2,3])
print(a1)
print('================')
print(np.percentile(a1, [0,20,40,60,80,100], interpolation='linear'),'linear')
print(np.percentile(a1, [0,20,40,60,80,100], interpolation='higher'),'higher')
print(np.percentile(a1, [0,20,40,60,80,100], interpolation='lower'),'lower')
print(np.percentile(a1, [0,20,40,60,80,100], interpolation='nearest'),'nearest')
print(np.percentile(a1, [0,20,40,60,80,100], interpolation='midpoint'),'midpoint')

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ] linear
[0 1 2 2 3 3] higher
[0 0 1 1 2 3] lower
[0 1 1 2 2 3] nearest
[0.  0.5 1.5 1.5 2.5 3. ] midpoint


#### any()

In [ ]:
a2 = np.array([
              [False,False,False],
              [False,True,True],
              [False,True,True]
              ])
print(a2)
print('================')

print(np.any(a2))
print('================')

print(np.any(a2, axis=0))
print('================')

print(np.any(a2, axis=1))

[[False False False]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[False  True  True]


#### all()

In [ ]:
a2 = np.array([
              [False,False,True],
              [True,True,True],
              [False,True,True]
              ])
print(a2)
print('================')

print(np.all(a2))
print('================')

print(np.all(a2, axis=0))
print('================')

print(np.all(a2, axis=1))

[[False False  True]
 [ True  True  True]
 [False  True  True]]
False
[False False  True]
[False  True False]


### 비교 연산(Comparison Operators)

|연산자|비교 범용 함수|
|---|---|
|==|np.equal|
|!=|np.not_equal|
|<|np.less|
|<=|np.less_equal|
|>|np.greater|
|>=|np.greater_equal|

In [ ]:
a1 = np.arange(1, 10)
print(a1)
print(a1 == 5)
print('=======================================================')
print(a1 != 5)
print('=======================================================')
print(a1 < 5)
print('=======================================================')
print(a1 <= 5)
print('=======================================================')
print(a1 > 5)
print('=======================================================')
print(a1 >= 5)
print('=======================================================')


[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True False False False False False]
[ True  True  True  True  True False False False False]
[False False False False False  True  True  True  True]
[False False False False  True  True  True  True  True]


In [ ]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
print('=======================================================')
print(np.sum(a2))
print('=======================================================')
print(np.count_nonzero(a2>5))
print('=======================================================')
print(np.sum(a2>5, axis=0))
print('=======================================================')
print(np.sum(a2>5, axis=1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
[1 1 2]
[0 1 3]


In [ ]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
print('=======================================================')
print(np.any(a2))
print('=======================================================')
print(np.count_nonzero(a2>5))
print('=======================================================')
print(np.any(a2>5, axis=0))
print('=======================================================')
print(np.any(a2>5, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
True
4
[ True  True  True]
[False  True  True]


In [ ]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
print('=======================================================')
print(np.all(a2))
print('=======================================================')
print(np.count_nonzero(a2>5))
print('=======================================================')
print(np.all(a2>5, axis=0))
print('=======================================================')
print(np.all(a2>5, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
True
4
[False False False]
[False False  True]


|비교 범용 함수|설명|
|---|---|
|np.isclose|배열 두개가(z*1e+02)% 내외로 가까우면 True, dkslaus False|
|np.isinf|배열이 inf이면 True, 아니면 False|
|np.isfinite|배열이 inf, nan이면 False, 아니면 True|
|np.isnan|배열이 nan이면 True, 아니면 False|

In [135]:
a1 = np.array([1,2,3,4,5])
print(a1)
print('=======================================================')

b1 = np.array([1,2,3,3,4])
print(b1)
print('=======================================================')
print(np.isclose(a1,b1))


[1 2 3 4 5]
[1 2 3 3 4]
[ True  True  True False False]


In [138]:
a1 = np.array([np.nan, 2, np.inf, 4, np.NINF])
print(a1)
print('=======================================================')
print(np.isnan(a1))
print('=======================================================')
print(np.isfinite(a1))

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False  True False  True False]



#### 불리언 연산자(Boolean Operators)

|연산자|비교 범용 함수|
|---|---|
|&|np.bitwise_and|
|\||np.bitwise_or|
|^|np.bitwise_xor|
|~|np.bitwise_not|


In [143]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)
print('\n')
print((a2 > 5) & (a2 < 8))
print('\n')

print(a2[(a2 > 5) & (a2 < 8)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[False False False]
 [False False  True]
 [ True False False]]


[6 7]


In [144]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)
print('\n')
print((a2 > 5) | (a2 < 8))
print('\n')

print(a2[(a2 > 5) | (a2 < 8)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


[1 2 3 4 5 6 7 8 9]


In [145]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)
print('\n')
print((a2 > 5) ^ (a2 < 8))
print('\n')

print(a2[(a2 > 5) ^ (a2 < 8)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[ True  True  True]
 [ True  True False]
 [False  True  True]]


[1 2 3 4 5 8 9]


In [147]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)
print('\n')
print(~(a2 > 5))
print('\n')

print(a2[~(a2 > 5)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[ True  True  True]
 [ True  True False]
 [False False False]]


[1 2 3 4 5]


### 배열정렬

In [148]:
a1 = np.random.randint(1, 10, size=10)

In [151]:
print(a1)
print('\n')
print(np.sort(a1))
print('\n')
print(a1)
print('\n')
print(np.argsort(a1))
print('\n')
print(a1)
print('\n')
print(a1.sort())
print(a1)

[4 4 5 5 5 5 5 5 7 9]


[4 4 5 5 5 5 5 5 7 9]


[4 4 5 5 5 5 5 5 7 9]


[0 1 2 3 4 5 6 7 8 9]


[4 4 5 5 5 5 5 5 7 9]


None
[4 4 5 5 5 5 5 5 7 9]


In [152]:
a2 = np.random.randint(1,10, size=(3,3))

In [154]:
print(a2)
print('\n')
print(np.sort(a2, axis=0))
print('\n')
print(np.sort(a2, axis=1))
print('\n')


[[3 2 5]
 [3 7 8]
 [8 2 8]]


[[3 2 5]
 [3 2 8]
 [8 7 8]]


[[2 3 5]
 [3 7 8]
 [2 8 8]]




#### 부분 정렬
- partition(): 배열에서 k개의 작은 값을 반환

In [156]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.partition(a1,3))

[4 1 1 7 3 8 3 3 8 5]
[1 1 3 3 3 4 8 7 8 5]


In [159]:
a2 = np.random.randint(1,10, size=(5,5))
print(a2)
print('\n')
print(np.partition(a2, 3))
print('\n')

print(np.partition(a2, 3, axis=0))
print('\n')

print(np.partition(a2, 3, axis=1))

[[3 7 5 1 8]
 [7 1 2 4 2]
 [6 5 1 2 8]
 [5 8 3 9 7]
 [8 5 4 3 6]]


[[1 3 5 7 8]
 [1 2 2 4 7]
 [2 1 5 6 8]
 [3 5 7 8 9]
 [3 4 5 6 8]]


[[5 1 3 1 7]
 [3 5 1 2 6]
 [6 5 2 3 2]
 [7 7 4 4 8]
 [8 8 5 9 8]]


[[1 3 5 7 8]
 [1 2 2 4 7]
 [2 1 5 6 8]
 [3 5 7 8 9]
 [3 4 5 6 8]]


### 배열입출력

|함수|설명|파일 종류|
|---|---|---|
|np.save()|Numpy 배열 객체 1개를 파일에 저장|바이너리|
|npsavez()|Numpy 배열 객체 여러개를 파일에 저장|바이너리|
|np.load()|Numpy 배열 객체 파일로부터 객체 로딩|바이너리|
|np.loadtxt()|텍스트 파일로부터 배열 로딩|텍스트|
|np.savetxt()|텍스트 파일에 Numpy 배열 객체 저장|텍스트|

In [160]:
a2 = np.random.randint(1, 10, size=(5,5))
print(a2)
np.save('a',a2)

[[9 2 4 4 5]
 [9 5 3 7 7]
 [1 1 8 2 3]
 [2 4 1 2 9]
 [1 1 5 9 2]]


In [161]:
!ls

a.npy  sample_data


In [163]:
b2 = np.random.randint(1,10, size=(5,5))
print(b2)
np.savez('ab',a2,b2)

[[6 7 5 1 4]
 [8 1 9 4 1]
 [6 3 9 9 8]
 [8 3 4 3 3]
 [6 6 7 7 7]]


In [164]:
!ls

ab.npz	a.npy  sample_data


In [165]:
npy = np.load('a.npy')
print(npy)

[[9 2 4 4 5]
 [9 5 3 7 7]
 [1 1 8 2 3]
 [2 4 1 2 9]
 [1 1 5 9 2]]


In [166]:
npz = np.load('ab.npz')
print(npz.files)

['arr_0', 'arr_1']


In [169]:
print(npz['arr_0'])
print('\n')
print(npz['arr_1'])

[[9 2 4 4 5]
 [9 5 3 7 7]
 [1 1 8 2 3]
 [2 4 1 2 9]
 [1 1 5 9 2]]


[[6 7 5 1 4]
 [8 1 9 4 1]
 [6 3 9 9 8]
 [8 3 4 3 3]
 [6 6 7 7 7]]


In [171]:
print(a2)
np.savetxt('a.csv', a2, delimiter=',')
!ls

[[9 2 4 4 5]
 [9 5 3 7 7]
 [1 1 8 2 3]
 [2 4 1 2 9]
 [1 1 5 9 2]]
ab.npz	a.csv  a.npy  sample_data


In [172]:
!cat a.csv

9.000000000000000000e+00,2.000000000000000000e+00,4.000000000000000000e+00,4.000000000000000000e+00,5.000000000000000000e+00
9.000000000000000000e+00,5.000000000000000000e+00,3.000000000000000000e+00,7.000000000000000000e+00,7.000000000000000000e+00
1.000000000000000000e+00,1.000000000000000000e+00,8.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00
2.000000000000000000e+00,4.000000000000000000e+00,1.000000000000000000e+00,2.000000000000000000e+00,9.000000000000000000e+00
1.000000000000000000e+00,1.000000000000000000e+00,5.000000000000000000e+00,9.000000000000000000e+00,2.000000000000000000e+00


In [177]:
!cd sample_data/

In [181]:
%cd ../

/content


In [180]:
%pwd

'/content/sample_data'

In [183]:
%ls

ab.npz  a.csv  a.npy  sample_data/


In [184]:
csv = np.loadtxt('a.csv', delimiter=',')
print(csv)

[[9. 2. 4. 4. 5.]
 [9. 5. 3. 7. 7.]
 [1. 1. 8. 2. 3.]
 [2. 4. 1. 2. 9.]
 [1. 1. 5. 9. 2.]]


In [185]:
print(b2)
np.savetxt('b.csv', b2, delimiter=',',fmt='%.2e', header='c1, c2, c3, c4, c5')

[[6 7 5 1 4]
 [8 1 9 4 1]
 [6 3 9 9 8]
 [8 3 4 3 3]
 [6 6 7 7 7]]


In [186]:
!cat b.csv

# c1, c2, c3, c4, c5
6.00e+00,7.00e+00,5.00e+00,1.00e+00,4.00e+00
8.00e+00,1.00e+00,9.00e+00,4.00e+00,1.00e+00
6.00e+00,3.00e+00,9.00e+00,9.00e+00,8.00e+00
8.00e+00,3.00e+00,4.00e+00,3.00e+00,3.00e+00
6.00e+00,6.00e+00,7.00e+00,7.00e+00,7.00e+00


In [188]:
csv = np.loadtxt('b.csv', delimiter=',')
print(csv)

[[6. 7. 5. 1. 4.]
 [8. 1. 9. 4. 1.]
 [6. 3. 9. 9. 8.]
 [8. 3. 4. 3. 3.]
 [6. 6. 7. 7. 7.]]


## 참고문헌 
- numpy, https://numpy.org/
- JakeVanderPlas, "Python Data Science Handbook", O'Reilly
- Wes Mckinney, "Python for Data Analysis", O'Reilly