<a href="https://colab.research.google.com/github/osori-magu/Nunpy-Onshot/blob/master/Numpy_%ED%95%9C%EB%B0%A9%EC%97%90_%EB%B0%B0%EC%9A%B0%EA%B8%B0%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 제대로 배우기


In [ ]:
import numpy as np

## NumPy 특징

## 배열생성

### 리스트로 배열 만들기

### 배열 생성 및 초기화
- zeros(): 모든 요소를 0으로 초기화

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

- ones(): 모든 요소를 1로 초기화

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

- full(): 모든 요소를 지정한 값으로 초기

In [ ]:
np.full((3,3),1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

- eye(): 단위행렬(identity matrix)생성
  - 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 - empty(): 초기화 되지 않은 배열 생성
  - 초기화가 없어서 배열 생성 비용이 저렴하고 빠름
  - 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있

In [ ]:
np.empty(10)

array([3.52858601e-316, 2.07955588e-312, 2.46151512e-312, 2.01589600e-312,
       2.35541533e-312, 2.33419537e-312, 2.44029516e-312, 2.05833592e-312,
       2.02566915e-322, 0.00000000e+000])

- _like(): 지정된 배열과 shape가 같은 행렬 생성 

   - np.zeros_like()
   - np.ones_like()
   - np.full_like()
   - np.empty_like()



In [ ]:
a1 = np.array([4,5,6,4,5])
np.zeros_like(a1)

array([0, 0, 0, 0, 0])

In [ ]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)

np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
a3 = np.array([
               [[1,2,3,], [4,5,6,], [7,8,9] ],
               [[1,2,3,], [4,5,6,], [7,8,9] ],
               [[1,2,3,], [4,5,6,], [7,8,9] ]
               ])

np.full_like(a3, 10)

array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

벡터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용된다. 선형 대수에 적용되는 벡터화 연산에 대해서는 나중에 보다 자세히 설명한다.

### 생성한 값으로 배열 생성

- arange(): 정수 범위로 배열 생성

In [ ]:
np.arange(0, 30, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

 - linspace(): 범위 내에서 균등 간격의 배열 생성


In [ ]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

 - logspace(): 범위 내에서 균등간격으로 로그 스케일로 배열 생성


In [ ]:
np.logspace(0.1, 1, 20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

### 랜덤값으로 배열 생성 

|함수|설명   |
|---|---|
|seed|난수 발생을 위한 시드 지정|
|permutation|순서를 임의로 바꾸거나 임의의 순열 반환|
|shuffle   |리스트나 배열의 순서를 뒤썩음   |
|random   |랜덤한 수의 배열 생성   |
|rand   |균등분포에서 표본 추출   |
|randint   |주어진 최소/최대 범위의 난수 추출   |
|bionomial|표준편차가1, 평균값 0인 정규분포의 표본 추출|
|normal   |정규분포(가우시안)에서 표본추출   |
|beta   |베타분포에서 표본 추출   |
|chisquare   |카이제곱분포에서 표본 추출   |
|gamma   |감마분포에서 표본 추출  |
|uniform   |균등(0,1)분포에서 포본추출  |

 - random.random(): 랜덤한 수의 배열 생성

In [ ]:
np.random.random((3,3))

array([[0.63051738, 0.30520104, 0.65202138],
       [0.37103748, 0.31553952, 0.93609849],
       [0.70203418, 0.45671637, 0.93951267]])

 - np.random.randint(): 일정한 구간의 랜덤 정수의 배열 생성

In [ ]:
np.random.randint(0,10, (3,3))

array([[6, 4, 4],
       [8, 8, 9],
       [8, 3, 8]])

 - random.normal(): 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성 
 - 평균 = 0, 표준편차=1, 3 x 3 배열
 

In [ ]:
#np.random.normal(0,1, (3,3))
np.random.normal(0,1, size=(3,3))

array([[-0.9943463 , -0.70194723,  0.19868181],
       [ 0.63117294, -0.02486868, -1.96901825],
       [ 0.18270469,  0.94544757,  0.25415279]])

 - random.rand(): 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생

In [ ]:
np.random.rand(3,3)

array([[0.16034721, 0.5369134 , 0.80400412],
       [0.76391048, 0.00165631, 0.02335572],
       [0.07565457, 0.42856592, 0.9319569 ]])

 - random.rand():표준정규분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성
 

In [ ]:
np.random.randn(3,3)

array([[-0.93825111, -1.202357  ,  0.46148983],
       [-0.68032374, -0.87394398,  1.46967569],
       [ 1.18870113,  0.64953186,  1.6155991 ]])

### 표준 데이터 타입

|데이터타입|설명|
|---|---|
|bool_|바이트로 저장된 Boolean으로 True or False값을 가짐|
|int_|Integer type|
|intc|C언어에서 사용되는 int와 동일(일반적으로 int32 또는 int64)|
|intp|인덱싱에 사용되는 정수(C언어에서 sszie_t와 동일; 일반적으로 int32 또는 int64)|
|int8|Byte(-128 to127)|
|int16|Integer(-32768 to 32767)|
|int32|Integer(-2147483648 to 2147483647)
|int64|Integer(-9223372036854775808 to 9223372036854775807)|
|uint8|부호 없는 정수/Unsigned integer (0 to 255)|
|uint16|부호 없는 정수/Unsigned integer (0 to 65535)|
|uint32|부호 없는 정수/Unsigned integer (0 to 4294967295)|
|uint64|부호 없는 정수/Unsigned integer (0 to 18446744073709551615)|
|float16|반정밀 부동 소수점(Half precision float):부호비트, 5비트 지수, 10비트 가수|
|float32|단정밀 부동 소수점(Single precision float):부호비트 8비트 지수, 23비트 가수|
|float64|배정밀 부동 소수점(Double precision float): 부호비트, 11비트 지수, 52비트 가수|
|float_|float64를 줄여서 표현|
|complex64|복소수(Complex number), 두 개의 32비트 부동 소수점으로 표현|
|complex128|복소, 두 개의 64비트 부동 소수점으로 표현|
|complex_|complex128를 줄여서 표현|


In [ ]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
np.full((3,3), 1.0, dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 날짜/시간 배열 생성 

|코드|의미|상대적 시간범위|절대적 시간범위|
|---|---|---|---|
|```Y``` |연     |±9.2e18 years    |[9.2e18 BC, 9.2e18 AD]    |
|```M``` |월     |±7.6e17 years    |[7.6e17 BC, 7.6e17 AD]    |
|```W``` |주     |±1.7e17 years    |[1.7e17 BC, 1.7e17 AD]    |
|```D``` |일     |±2.5e16 years    |[2.5e16 BC, 2.5e16 AD]    |
|```h``` |시     |±1.0e15 years    |[1.0e15 BC, 1.0e15 AD]    |
|```m``` |분     |±1.7e13 years    |[1.7e13 BC, 1.7e13 AD]    |
|```s``` |초     |±2.9e11 years    |[2.9e11 BC, 2.9e11 AD]    |
|```ms```|밀리초|±2.9e8 years   |[ 2.9e8 BC, 2.9e8 AD]    |
|```us```|마이크로초|±2.9e5 years    |[ 290301 BC, 294241 AD]    |
|```ns```|나노초|±292 years    |[ 1678 AD, 2262 AD]    |
|```ps```|피코초|±106 days    |[ 1969 AD, 1970 AD]    |
|```fc```|펨토초|±2.6 hours    |[ 1969 AD, 1970 AD]    |
|```as```|아토초|±9.2 seconds    |[ 1969 AD, 1970 AD]   |

In [ ]:
date = np.array('2020-01-01', dtype=np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [ ]:
date + np.arange(3)

array(['2020-01-01', '2020-01-02', '2020-01-03'], dtype='datetime64[D]')

In [ ]:
datetime = np.datetime64('2020-06-01 12:00')
datetime

numpy.datetime64('2020-06-01T12:00')

In [ ]:
datetime = np.datetime64('2020-01-01 12:00:12.34', 'ns')
datetime

numpy.datetime64('2020-01-01T12:00:12.340000000')

## 배열조희


### 배열 속성 정보 

In [ ]:
def array_info(array):
  print(array)
  print('ndim:', array.ndim)
  print('shape:', array.shape)
  print('dtype:', array.dtype)
  print('size:', array.size)
  print('itemsize:', array.itemsize)
  print('nbytes:', array.nbytes)
  print('strides:', array.strides)

In [ ]:
a1 = np.array([4,5,6,4,5])
array_info(a1)
# ndim은 차원의 개수
# shape은 5개의 element가 있다는것/ 1행 5열(1row 5columns)
# dtype int인 정수값 사용
# size는 5개의 element를 말하조.
# itemsize는 각 하나의 item의 byte크기를 말함 즉, 8byte
# nbytes는 40의미가 각 itemsize 8 * 5개
# 한개 elements를 넘어가기 위해서는 8byte가 필요함 / 3차원->2차원->1차원 넘어갈때 필요한 bytes크기

[4 5 6 4 5]
ndim: 1
shape: (5,)
dtype: int64
size: 5
itemsize: 8
nbytes: 40
strides: (8,)


In [ ]:
array_info(a2)
# strides 다음 row로 넘어갈때 필요한게 24bytes
# 3차원->2차원->1차원 넘어갈때 필요한 bytes크기

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape: (3, 3)
dtype: int64
size: 9
itemsize: 8
nbytes: 72
strides: (24, 8)


In [ ]:
array_info(a3)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]
ndim: 3
shape: (2, 3, 4)
dtype: int64
size: 24
itemsize: 8
nbytes: 192
strides: (96, 32, 8)


### 인덱싱(Indexing)

In [ ]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[4 5 6 4 5]
4
6
5
4


In [ ]:
print(a2)
print(a2[0,0])
print(a2[0,2])
print(a2[1,-1])
print(a2[2,-2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
6
8


In [ ]:
print(a3)
print(a3[0,0,0])
print(a3[1,1,1])
print(a3[1,2,2])
print(a3[1,-1,-2])

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]
1
16
21
21


### 슬라이싱(Slicing)

 - 슬라이싱 구문: **```a[start:stop:step]```**
 - 기본값: start =0, stop =ndim, step=1


In [ ]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[::2])
print(a1[::-1])

[4 5 6 4 5]
[4 5]
[4 5 6 4 5]
[4]
[4 6 5]
[5 4 6 5 4]


In [ ]:
print(a2)
print('-----')
print(a2[1])
print('-----')

print(a2[1, :])

print('-----')
print(a2[:2, :2])

print('-----')
print(a2[1:,  ::-1])

print('-----')
print(a2[::-1, ::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-----
[4 5 6]
-----
[4 5 6]
-----
[[1 2]
 [4 5]]
-----
[[6 5 4]
 [9 8 7]]
-----
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### Boolean Indexing
- 배열 각 요소의 선택 여부를 True or False로 지정
- True 값인 인덱스의 값만 조회

In [ ]:
print(a1)
bi = [False, True, True, False, True]
print(a1[bi])
bi = [True, False, True, True, False]
print(a1[bi])

[4 5 6 4 5]
[5 6 5]
[4 6 4]


In [ ]:
print(a2)
bi = np.random.randint(0,2, (3,3), dtype=bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False  True]
 [ True  True False]
 [ True  True False]]
[3 4 5 7 8]


### Fancy Indexing

In [ ]:
print(a1)
print(a1[0],a1[2])
ind = [0,2]
print(a1[ind])
ind = np.array([
                [0,1],
                [2,0]
              ])
print(a1[ind])

[4 5 6 4 5]
4 6
[4 6]
[[4 5]
 [6 4]]


In [ ]:
print(a2)
row = np.array([0,2])
col = np.array([1,2])
print('=======')

print(a2[row, col])

print('=======')
print(a2[row, :])
print('=======')
print(a2[:, col])
print('=======')


print(a2[row, 1])

print('=======')
print(a2[2, col])
print('=======')
print(a2[row, 1:])
print('=======')
print(a2[1:, col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[2 8]
[8 9]
[[2 3]
 [8 9]]
[[5 6]
 [8 9]]


## 배열 값 삽입/수정/삭제/복

### 배열 값 삽입 

 - ```insert():```: 배열의 특정 위치에 값 삽입 
 - axis를 지정하지 않으면 1차원 배열로 변환
 - 추가할 방향을 axis로 지정
 - 원본 배열 변경없이 새로운 배열 반환
 

In [ ]:
print(a1)
b1 = np.insert(a1, 0, 10)
print(b1)
print(a1)
c1 = np.insert(a1, 2, 10)
print(c1)

[4 5 6 4 5]
[10  4  5  6  4  5]
[4 5 6 4 5]
[ 4  5 10  6  4  5]


In [ ]:
print(a2)
print('===')
b2 = np.insert(a2, 1,10, axis=0)
print(b2)
print('===')
c2 = np.insert(a2,1, 10, axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
===
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
===
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정 
 - 배열의 인덱싱으로 접근하여 값 수정

In [ ]:
print(a1)
a1[0] = 1
a1[1] = 2
a1[2] = 3
print(a1)
a1[:1] = 9
print(a1)


[9 2 3 4 5]
[1 2 3 4 5]
[9 2 3 4 5]


In [ ]:
i = np.array([1,3,4])
a1[i] = 0
a1[i] += 4

print(a1)

[9 4 3 4 4]


In [ ]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)
a2[0,0]=1
print('===')
a2[1,1]=2
print(a2)
a2[2,2]=3
print('===')

a2[0]=1
print(a2)
print('===')
a2[1:, 2] = 9
print(a2)
print('===')
a2[row, col] = 0
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
===
[[1 2 3]
 [4 2 6]
 [7 8 9]]
===
[[1 1 1]
 [4 2 6]
 [7 8 3]]
===
[[1 1 1]
 [4 2 9]
 [7 8 9]]
===
[[1 0 1]
 [4 2 9]
 [7 8 0]]


### 배열 값 삭제 
- delete(): 배열의 특정 위치에 값 삭제
- axis를 지정하지 않으면 1차원 배열로 변환
- 삭제할 방향을 axis로 지정
- 원본 배열 변경없이 새로운 배열 반환


In [ ]:
print(a1)
b1 = np.delete(a1,1)
print(b1)
print(a1)

[9 4 3 4 4]
[9 3 4 4]
[9 4 3 4 4]


In [ ]:
print(a2)
print('===')
print()
b2 = np.delete(a2, 1, axis=0)
print(b2)
print('===')
c2 = np.delete(a2, 1, axis=1)
print(c2)

[[1 0 1]
 [4 2 9]
 [7 8 0]]
===

[[1 0 1]
 [7 8 0]]
===
[[1 1]
 [4 9]
 [7 0]]


### 배열 복사
- 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님 


In [ ]:
print(a2)
print('===')
print(a2[:2, :2])
a2_sub = a2[:2, :2]
print('===')
print(a2_sub)
print('===')
a2_sub[:, 1] = 0
print(a2_sub)
print('===')
print(a2)


[[1 0 1]
 [4 0 9]
 [7 8 0]]
===
[[1 0]
 [4 0]]
===
[[1 0]
 [4 0]]
===
[[1 0]
 [4 0]]
===
[[1 0 1]
 [4 0 9]
 [7 8 0]]


 - copy(): 배열이나 하위 배열 내의 값을 명시적으로 복사

In [ ]:
print(a2)
print('===')
a2_sub_copy = a2[:2, :2].copy()
print(a2_sub_copy)
a2_sub_copy[:, 1]=1
print('===')
print(a2_sub_copy)
print(a2)

[[1 0 1]
 [4 0 9]
 [7 8 0]]
===
[[1 0]
 [4 0]]
===
[[1 1]
 [4 1]]
[[1 0 1]
 [4 0 9]
 [7 8 0]]


## 배열 변환 


### 배열 전치 및 축 변경

In [ ]:
print(a2)
print('===')
print(a2.T)

[[1 0 1]
 [4 0 9]
 [7 8 0]]
===
[[1 4 7]
 [0 0 8]
 [1 9 0]]


In [ ]:
print(a3)
print('==================')
print(a3.T)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]
[[[ 1 11]
  [ 5 15]
  [ 9 19]]

 [[ 2 12]
  [ 6 16]
  [10 20]]

 [[ 3 13]
  [ 7 17]
  [11 21]]

 [[ 4 14]
  [ 8 18]
  [12 22]]]


In [ ]:
print(a2)
print('==================')
print(a2.swapaxes(1,0))

[[1 0 1]
 [4 0 9]
 [7 8 0]]
[[1 4 7]
 [0 0 8]
 [1 9 0]]


In [ ]:
print(a3)
print('==================')
print(a3.swapaxes(0,1))
print('==================')
print(a3.swapaxes(1,2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


### 배열 재구조화

- reshape(): 배열의 형상을 변경

In [ ]:
n1 = np.arange(1, 10)
print(n1)
print(n1.reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


- newaxis(): 새로운 축 추가

In [ ]:
print(n1)
print('==================')

print(n1[np.newaxis, :5])
print('==================')

print(n1[:5, np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### 배열 크기 변경

- 배열 모양만 변경

In [ ]:
n2 = np.random.randint(0, 3, (2,5))
print(n2)
print('==================')
n2.resize((5,2))
print((n2))

[[1 2 0 2 0]
 [1 2 1 0 1]]
[[1 2]
 [0 2]
 [0 1]
 [2 1]
 [0 1]]


 - 배열 크기 증가
 - 남은 공간은 0으로 채워짐

In [ ]:
n2.resize((5,5))
print((n2))

[[1 2 0 2 0]
 [1 2 1 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


- 배열 크기 감소
- 포함되지 않은 값은 삭제됨


In [ ]:
n2.resize((4,4))
print(n2)
print('==================')
n2.resize((3,3))
print(n2)

[[1 2 0 2]
 [0 1 2 1]
 [0 0 0 0]
 [0 0 0 0]]
[[1 2 0]
 [2 0 1]
 [2 1 0]]


### 배열추가

- append(): 배열의 끝에 값 추가

In [ ]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
print('==================')
b2 = np.arange(10,19).reshape(3,3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


- axis 지정이 없으면 1차원 배열 형태로 변형되어 결

In [ ]:
c2 = np.append(a2, b2)
print('==================')
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


- axis를 0으로 지정
- shape[0]을 제외한 나머지 shape는 같아야 

In [ ]:
c2 = np.append(a2, b2, axis=0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


- axis를 1로 지정
- shape[1]을 제외한 나머지 shape은 같아야 함 

In [ ]:
c2 = np.append(a2, b2, axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결 

- concatenate(): 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [ ]:
a1 = np.array([1,3,5])
b1 = np.array([2,4,6])
np.concatenate([a1,b1])


array([1, 3, 5, 2, 4, 6])

In [ ]:
c1 = np.array([7,8,9])
np.concatenate([a1,b1,c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [ ]:
a2 = np.array([
              [1,2,3],
              [4,5,6]])
np.concatenate([a2,b2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

- vstack(): 수직 스택(vertical stack), 1차원으로 연결 

In [ ]:
np.vstack([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

- hstack(): 수평 스택(horizontal stack), 2차원으로 연

In [ ]:
np.hstack([a2,a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

- dstack(): 깊이 스택(depth stack), 3차원으로 연결


---



In [ ]:
np.dstack([a2, a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

- stack(): 새로운 차원으로 연결 


In [ ]:
np.stack([a2,a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

## 배열분

- split(): 배열분할 

In [ ]:
a1 = np.arange(0,10)
print(a1)
b1, c1 = np.split(a1, [5])
print('---------------')
print(b1,c1)
print('---------------')
b1, c1 = np.split(a1, [2,4,6,8])


[0 1 2 3 4 5 6 7 8 9]
---------------
[0 1 2 3 4] [5 6 7 8 9]


- vsplit(): 수직분할, 1차원으로 분

- hsplit(): 수평분할, 2차원으로 분

- dsplit(): 깊이 분할, 3차원으로 분할